(()=>{'use strict';const $=id=>document.getElementById(id),G=window.QuestionGenerator;
const area=document.createElement('div');area.className='teacher-box generator-box';area.innerHTML='<h3>Generate focused practice</h3><label>What should students practice?<textarea id="generation-prompt" maxlength="300" placeholder="Examples: HTML basics; CSS class and ID selectors; CSS box model calculations"></textarea></label><label>Number of questions<input id="generation-count" type="number" min="1" max="40" value="10"></label><button id="generate-questions">Generate questions</button><p class="small">Uses built-in templates and reviewed library questions. Supported topics are listed on the left. Blank description uses your selected topics. Question depth follows the setting above. Review the questions before assigning them.</p>';
$('lesson-preview').parentElement.before(area);
function random(a){return a[Math.floor(Math.random()*a.length)];}
function make(topic,subject,text,answer,wrong,explanation){const answers=[answer,...wrong];for(let i=3;i>0;i--){const j=Math.floor(Math.random()*(i+1));[answers[i],answers[j]]=[answers[j],answers[i]];}return {topic,subject,text,answers,correct:answers.indexOf(answer),explanation};}
function variant(subject,domain,depth){const token=random(['hero','quest','forest','spell','party','treasure'])+Math.floor(10+Math.random()*90);
if(domain!=='HTML'&&subject==='Selectors'){const id=Math.random()<.5;return make('CSS',subject,`Which selector targets ${id?'id':'class'}="${token}"?`,(id?'#':'.')+token,[(id?'.':'#')+token,token,'@'+token],id?'An ID selector starts with #.':'A class selector starts with a dot.');}
if(domain!=='HTML'&&subject==='Box model'){const w=Math.floor(5+Math.random()*20)*10,p=Math.floor(1+Math.random()*10),b=Math.floor(1+Math.random()*4);if(depth!=='beginner')return make('CSS',subject,`An element uses content-box, width: ${w}px, padding: ${p}px and border: ${b}px. What is its outer width excluding margin?`,(w+2*p+2*b)+'px',[w+'px',(w+p+b)+'px',(w+2*p)+'px'],`Add both sides: ${w} + ${2*p} padding + ${2*b} border = ${w+2*p+2*b}px.`);return make('CSS',subject,`Which declaration adds ${p}px of space inside the border of .${token}?`,`padding: ${p}px`,[`margin: ${p}px`,`gap: ${p}px`,`outline: ${p}px`],'Padding adds space between content and its border.');}
if(domain!=='HTML'&&subject==='Typography'){const color=random(['red','blue','green','purple','navy','teal']);return make('CSS',subject,`Which declaration makes text in .${token} ${color}?`,`color: ${color}`,[`font-color: ${color}`,`text-color: ${color}`,`background-color: ${color}`],'color sets the foreground text color.');}
if(domain!=='HTML'&&subject==='Layout & responsive design'&&depth!=='beginner'){const width=random([480,600,768,900,1024]);return make('CSS',subject,`Which media query applies at viewport widths of ${width}px or narrower?`,`@media (max-width: ${width}px)`,[`@media (min-width: ${width}px)`,`@media (width > ${width}px)`,`@media (width = ${width}px)`],'max-width matches viewports at or below the specified width.');}
if(domain!=='CSS'&&subject==='Links & images'){const file=token+'.html';return make('HTML',subject,`Which markup links to ${file}?`,`<a href="${file}">Open</a>`,[`<a src="${file}">Open</a>`,`<p href="${file}">Open</p>`,`<a link="${file}">Open</a>`],'An anchor uses href to specify its destination.');}
if(domain!=='CSS'&&subject==='Forms & accessibility'){return make('HTML',subject,`Which label correctly associates with an input whose id is "${token}"?`,`<label for="${token}">Name</label>`,[`<label href="${token}">Name</label>`,`<label name="${token}">Name</label>`,`<label src="${token}">Name</label>`],'The label’s for attribute matches the input’s id.');}
if(domain!=='CSS'&&subject==='Structure & semantics'){const task=random(['navigation links','main article content','an unordered list','the highest-level page heading']),good={'navigation links':'<nav>','main article content':'<main>','an unordered list':'<ul>','the highest-level page heading':'<h1>'}[task];return make('HTML',subject,`You are building ${token}. Which element is appropriate for ${task}?`,good,['<span>','<br>','<style>'],'Choose the semantic element matching the content’s purpose.');}return null;}
$('generate-questions').onclick=()=>{const text=$('generation-prompt').value.trim(),lower=text.toLowerCase(),count=Number($('generation-count').value);if(!Number.isInteger(count)||count<1||count>40){$('teacher-message').textContent='Choose between 1 and 40 questions.';return;}if(text){const html=/html|tags|markup|semantic|forms|accessibility|links|images/.test(lower),css=/css|selectors|properties|box model|padding|margin|flex|grid|responsive|typography/.test(lower);if(!html&&!css){$('teacher-message').textContent='Use a supported HTML or CSS topic, or leave the description blank and select topics on the left.';return;}const domain=html&&css?'Both':css?'CSS':'HTML',matches=[];if(/selector|class|\bid\b/.test(lower))matches.push('Selectors');if(/padding|margin|box model|border/.test(lower))matches.push('Box model');if(/layout|flex|grid|responsive|media quer/.test(lower))matches.push('Layout & responsive design');if(/font|typography|color|text/.test(lower))matches.push('Typography');if(/link|image|href|src/.test(lower))matches.push('Links & images');if(/form|accessib|input|label/.test(lower))matches.push('Forms & accessibility');if(/semantic|structure|heading|list/.test(lower))matches.push('Structure & semantics');G.preset(domain,matches.length?matches:G.topics,$('teacher-difficulty').value);}
const available=G.selected(),subjects=[...new Set(available.map(q=>q.subject))],domain=$('teacher-domain').value,depth=$('teacher-difficulty').value;if(!subjects.length){$('teacher-message').textContent='No matching topics at this depth. Choose another topic or increase question depth.';return;}const out=[],seen=new Set();for(let i=0;i<250&&out.length<count;i++){const q=i%3===0?random(available):variant(random(subjects),domain,depth);if(q&&!seen.has(q.text)){seen.add(q.text);out.push({...q,answers:[...q.answers]});}}G.add(out,text||'Focused '+domain+' practice');if(out.length<count)$('teacher-message').textContent=`Prepared ${out.length} distinct questions for this topic and depth. Select more topics to increase variety.`;};
})();
