(()=>{'use strict';
const $=id=>document.getElementById(id);let KEY='web-wizardry-v1';const encounters=[{name:'The Mossgate',enemy:'Briar Imp',hp:145,damage:18,xp:60,gold:25,treasure:'Mossgate copper seal'},{name:'Whispering Hollow',enemy:'Thornfang Wolf',hp:185,damage:23,xp:85,gold:40,treasure:'Moonstone charm'},{name:'The Ancient Crossing',enemy:'Runebark Sentinel',hp:225,damage:27,xp:110,gold:55,treasure:'Runebark key'},{name:'Heart of the Forest',enemy:'Forest Guardian',hp:305,damage:32,xp:160,gold:100,treasure:'Emerald crown of the forest'}];
let state=null,question=null,busy=false,renderers=[],sound=false,audio=null;
function bank(){return state?.lesson?.questions||QUESTIONS;}
function encounter(){const e=encounters[state.encounter],p=state.lesson?.pace||'standard',hp=p==='challenge'?1.2:1,damage=p==='practice'?.6:p==='challenge'?1.3:1;return {...e,hp:Math.round(e.hp*hp),damage:Math.round(e.damage*damage)};}
function readSave(){try{const s=JSON.parse(localStorage.getItem(KEY));if(!s||s.version!==1||!Number.isInteger(s.encounter)||s.encounter<0||s.encounter>3||!['battle','victory','defeat','complete'].includes(s.phase)||!Array.isArray(s.hp)||s.hp.length!==4||s.hp.some(x=>!Number.isFinite(x)||x<0)||!Number.isFinite(s.enemyHp)||!Number.isInteger(s.level)||s.level<1||s.level>20||!Number.isFinite(s.xp)||!Number.isFinite(s.gold)||!Number.isInteger(s.qIndex)||s.qIndex<0||!Array.isArray(s.order)||s.order.length!==(s.lesson?.questions||QUESTIONS).length||new Set(s.order).size!==(s.lesson?.questions||QUESTIONS).length||s.order.some(x=>!Number.isInteger(x)||x<0||x>=(s.lesson?.questions||QUESTIONS).length)||!Array.isArray(s.treasure)||!Number.isInteger(s.actor)||s.actor<0||s.actor>3)return null;if(s.lesson&&!window.validLesson?.(s.lesson))return null;return s;}catch{return null;}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$('save-status').textContent='Journey saved';}catch{$('save-status').textContent='Saving unavailable · keep this tab open';}}
function show(id){for(const x of ['title','battle','result','teacher'])$(x).hidden=x!==id;}
function maxHp(i){return HEROES[i].maxHp+(state.level-1)*12;}
function shuffled(){const a=bank().map((q,i)=>i);for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function start(lesson=null){state={version:1,phase:'battle',encounter:0,enemyHp:encounters[0].hp,hp:HEROES.map(h=>h.maxHp),level:1,xp:0,gold:0,treasure:[],lesson,qIndex:0,order:[],actor:0,turn:1,correct:0,wrong:0};state.order=shuffled();state.enemyHp=encounter().hp;save();battle();}
function title(){KEY='web-wizardry-v1';show('title');const own=readSave();KEY='web-wizardry-teacher-save-v1';const assigned=readSave();KEY='web-wizardry-v1';$('continue-teacher').disabled=!assigned;$('continue').disabled=!readSave();$('save-note').textContent=readSave()?'Your saved journey is ready.':'A new adventure awaits.';}
function heroSvg(h,i){const weapon=i===0?'<path d="M79 61L91 19" stroke="#c0a775" stroke-width="7"/><path d="M80 23Q114 10 105 45L84 36Z" fill="#c8d3d7"/>':i===1?'<path d="M81 74L84 22" stroke="#b79563" stroke-width="8"/><rect x="66" y="15" width="38" height="22" rx="4" fill="#b0c0c7"/>':i===2?'<path d="M85 25Q119 54 85 89M85 25L85 89" fill="none" stroke="#d1b078" stroke-width="4"/>':'<path d="M83 90L91 17" stroke="#94734c" stroke-width="7"/><circle cx="92" cy="17" r="10" fill="#aa83ef"/><circle cx="92" cy="17" r="5" fill="#e7d5ff"/>';
return `<svg viewBox="0 0 120 130" aria-hidden="true"><ellipse cx="59" cy="120" rx="35" ry="6" fill="#0006"/><path d="M34 79L26 115H91L80 77Z" fill="${h.color}"/><path d="M40 97L38 119M72 97L76 119" stroke="#394047" stroke-width="13"/><path d="M37 78L23 96M78 78L91 68" stroke="${h.color}" stroke-width="15" stroke-linecap="round"/><circle cx="59" cy="48" r="27" fill="#e2b795"/><path d="M31 43Q27 10 59 14Q93 13 87 44L74 32L36 39Z" fill="${i<2?'#807b73':i===2?'#c1a66d':'#59425f'}"/>${i<2?'<path d="M34 60Q58 120 84 60L66 69L58 63L48 70Z" fill="'+(i===0?'#aa794d':'#b9b3a6')+'"/>':''}<circle cx="49" cy="49" r="3" fill="#263236"/><circle cx="69" cy="49" r="3" fill="#263236"/>${i===2?'<path d="M34 43L19 35L30 57M85 43L99 34L89 57" fill="#e2b795"/>':''}${i===3?'<path d="M22 33L64 0L84 34Z" fill="#745b97"/><path d="M22 34H91" stroke="#b79cda" stroke-width="7"/>':''}${weapon}</svg>`;}
function enemySvg(){const crops=[[0,580,280,370],[280,505,400,445],[674,407,421,543],[1050,112,486,846]], [x,y,w,h]=crops[state.encounter];return `<svg viewBox="${x} ${y} ${w} ${h}" aria-hidden="true"><defs><clipPath id="enemy-clip"><rect x="${x}" y="${y}" width="${w}" height="${h}"/></clipPath></defs><image clip-path="url(#enemy-clip)" href="assets/enemies.webp" width="1536" height="1024"/></svg>`;}
function battle(){busy=false;show('battle');renderers.forEach(r=>r.destroy());$('heroes').innerHTML=HEROES.map((h,i)=>`<div class="hero hero-${i}" id="hero-${i}" style="--hero:${h.color}">${h.image?'':heroSvg(h,i)}</div>`).join('');renderers=HEROES.map((h,i)=>new CharacterRenderer($('hero-'+i),h));$('enemy-art').innerHTML=enemySvg();update();ask();}
function update(){const e=encounter();$('encounter-name').textContent=e.name;$('enemy-name').textContent=e.enemy;$('enemy-hp').textContent=`${Math.max(0,state.enemyHp)} / ${e.hp} HP`;$('enemy-bar').style.width=Math.max(0,state.enemyHp)/e.hp*100+'%';$('wallet').textContent=`Level ${state.level} · ${state.xp} XP · ${state.gold} gold`;$('trail').innerHTML=encounters.map((e,i)=>`<span class="${i===state.encounter?'current':i<state.encounter?'done':''}">${i<state.encounter?'✓':i+1} ${e.name}</span>`).join('');$('party').innerHTML=HEROES.map((h,i)=>`<div class="party-card ${i===state.actor?'active':''}"><strong>${h.name} <small>${h.role}</small></strong><div class="bar"><i style="width:${state.hp[i]/maxHp(i)*100}%;background:${h.color}"></i></div><span>${state.hp[i]} / ${maxHp(i)} HP ${state.hp[i]===0?'· Fallen':''}</span></div>`).join('');renderers.forEach((r,i)=>r.setState(state.hp[i]>0?'idle':'defeat'));}
function ask(){if(state.qIndex>0&&state.qIndex%bank().length===0){state.order=shuffled();save();}question=bank()[state.order[state.qIndex%bank().length]];$('school').textContent=question.topic+' · '+(state.lesson?state.lesson.name:'KNOWLEDGE CHECK');$('turn').textContent=`Turn ${state.turn} · ${HEROES[state.actor].name} is ready`;$('question').textContent=question.text;$('answers').innerHTML='';question.answers.forEach((a,i)=>{let b=document.createElement('button');b.textContent=`${String.fromCharCode(65+i)}  ${a}`;b.onclick=()=>answer(i);$('answers').append(b);});$('feedback').textContent='';$('next-question').hidden=true;}
function tone(good){if(!sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=good?660:165;g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.22);o.start();o.stop(audio.currentTime+.23);}catch{}}
async function effect(type,from,to){const box=$('arena').getBoundingClientRect(),a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),x=a.left+a.width/2-box.left,y=a.top+a.height/2-box.top,tx=b.left+b.width/2-box.left,ty=b.top+b.height/2-box.top;const p=document.createElement('div');p.className='effect '+type;p.style.left=x+'px';p.style.top=y+'px';p.textContent=type==='arrow'?'➶':type==='hammer'?'✦':type==='fireball'?'':type==='enemy-spell'?'✧':'╱';$('effects').append(p);const animation=p.animate([{transform:'translate(0,0) scale(.6)',opacity:1},{transform:`translate(${tx-x}px,${ty-y}px) scale(1.4)`,opacity:1}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?80:520,easing:'ease-in'});await animation.finished;p.remove();const hit=document.createElement('div');hit.className='impact';hit.style.left=tx+'px';hit.style.top=ty+'px';$('effects').append(hit);await hit.animate([{transform:'translate(-50%,-50%) scale(.2)',opacity:1},{transform:'translate(-50%,-50%) scale(2)',opacity:0}],{duration:250}).finished;hit.remove();}
async function answer(index){if(busy||state.phase!=='battle')return;busy=true;const good=index===question.correct;[...$('answers').children].forEach((b,i)=>{b.disabled=true;if(i===question.correct)b.classList.add('correct');if(i===index&&!good)b.classList.add('incorrect');});tone(good);let detail='';if(good){let actor=state.actor,damage=HEROES[actor].power+(state.level-1)*5;renderers[actor].setState('attack');await effect(HEROES[actor].effect,$('hero-'+actor),$('enemy-art'));state.enemyHp=Math.max(0,state.enemyHp-damage);state.correct++;detail=`${HEROES[actor].name} deals ${damage} damage. `;}else{const alive=state.hp.map((hp,i)=>hp>0?i:-1).filter(i=>i>=0),target=alive[(state.turn-1)%alive.length],damage=encounter().damage;await effect('enemy-spell',$('enemy-art'),$('hero-'+target));state.hp[target]=Math.max(0,state.hp[target]-damage);renderers[target].setState(state.hp[target]?'hurt':'defeat');state.wrong++;detail=`${encounters[state.encounter].enemy} hits ${HEROES[target].name} for ${damage} HP. `;}state.turn++;state.qIndex++;do{state.actor=(state.actor+1)%4;}while(state.hp.some(h=>h>0)&&state.hp[state.actor]===0);if(state.enemyHp===0)win();else if(state.hp.every(h=>h===0)){state.phase='defeat';save();result();}else{save();update();$('feedback').textContent=detail+question.explanation;$('next-question').hidden=false;$('next-question').focus();} }
function win(){const e=encounter();state.xp+=e.xp;state.gold+=e.gold;state.treasure.push(e.treasure);const level=1+Math.floor(state.xp/120);state.level=level;state.hp=HEROES.map((h,i)=>maxHp(i));state.phase=state.encounter===3?'complete':'victory';save();result();}
function result(){busy=false;show('result');const dead=state.phase==='defeat',complete=state.phase==='complete',e=encounters[state.encounter];$('result-eyebrow').textContent=dead?'THE FOREST REMEMBERS':complete?'CHAPTER COMPLETE':'ENCOUNTER CLEARED';$('result-title').textContent=dead?'A chance to rise':complete?'The forest is free':'Victory!';$('result-copy').textContent=dead?'Your party has fallen. Retry this encounter with full health. Your earlier rewards remain.':complete?'The Forest Guardian yields. Your knowledge restored the ancient path.':'The path opens ahead. Your party rests and recovers all HP.';$('reward').textContent=dead?`${state.correct} correct answers · ${state.wrong} mistakes`:`+${e.xp} XP · +${e.gold} gold · ${e.treasure}\nParty level ${state.level} · Total ${state.gold} gold`;$('advance').textContent=dead?'Retry encounter':complete?'Play again':'Follow the forest path →';}
$('start').onclick=()=>{KEY='web-wizardry-v1';if(readSave()){ $('save-note').textContent='A saved journey exists. Start again to replace it.';if($('start').dataset.confirm!=='yes'){$('start').dataset.confirm='yes';$('start').textContent='Confirm new adventure';return;}}start();};$('continue').onclick=()=>{KEY='web-wizardry-v1';state=readSave();if(!state)return;state.phase==='battle'?battle():result();};$('next-question').onclick=()=>{busy=false;ask();};$('advance').onclick=()=>{if(state.phase==='complete'){start(state.lesson||null);return;}if(state.phase==='victory')state.encounter++;state.phase='battle';state.hp=HEROES.map((h,i)=>maxHp(i));state.enemyHp=encounter().hp;state.actor=0;save();battle();};$('menu').onclick=title;$('home').onclick=e=>{e.preventDefault();if(!busy)title();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';tone(true);};document.addEventListener('keydown',e=>{if(e.repeat||$('battle').hidden)return;if(!busy&&['1','2','3','4'].includes(e.key))answer(+e.key-1);else if(e.key==='Enter'&&!$('next-question').hidden)$('next-question').click();});window.GameModes={title,showTeacher(){show('teacher');},startTeacher(lesson){if(!window.validLesson(lesson))return;KEY='web-wizardry-teacher-save-v1';start(JSON.parse(JSON.stringify(lesson)));}};
$('continue-teacher').onclick=()=>{KEY='web-wizardry-teacher-save-v1';state=readSave();if(!state)return;state.phase==='battle'?battle():result();};title();
})();
