(()=>{'use strict';
const $=id=>document.getElementById(id),storage='web-wizardry-teacher-v1';
const topics=['Links & images','Structure & semantics','Forms & accessibility','Selectors','Box model','Layout & responsive design','Typography'];
const tags=[0,0,6,3,1,4,3,1,5,1,6,4,1,5,2,4,1,6,2,3];
QUESTIONS.forEach((q,i)=>{q.subject=topics[tags[i]];q.difficulty=[8,11,13,15,17,19].includes(i)?'intermediate':'beginner';});
const extras=[
['CSS','Selectors','advanced','Which selector has the highest specificity?',['.card p','#quest','main .card','p:hover'],1,'An ID selector has greater specificity than these class and type selectors.'],
['CSS','Layout & responsive design','advanced','What does grid-template-columns: repeat(3, 1fr) create?',['Three equal flexible columns','Three fixed pixels','Three rows','A single column'],0,'repeat(3, 1fr) creates three tracks sharing available space equally.'],
['CSS','Box model','advanced','A content-box element has width: 100px, padding: 10px and border: 2px. What is its outer width excluding margin?',['100px','112px','120px','124px'],3,'100 + 20 pixels of horizontal padding + 4 pixels of borders = 124px.'],
['HTML','Forms & accessibility','intermediate','Which input attribute requires a value before form submission?',['required','checked','placeholder','readonly'],0,'required enables the browser’s built-in empty-value validation.'],
['HTML','Structure & semantics','advanced','Which element is suited to a self-contained article that could be distributed independently?',['<span>','<article>','<aside>','<br>'],1,'article represents a self-contained composition.'],
['CSS','Typography','advanced','Which line-height generally scales proportionally with each element’s font size?',['20px','1.5','150px','0px'],1,'A unitless line-height is multiplied by the element’s own font size.'],
['HTML','Links & images','intermediate','Which image attribute lets the browser choose among different source resolutions?',['srcset','href','for','poster'],0,'srcset supplies candidate image sources and descriptors.'],
['CSS','Selectors','intermediate','Which selector matches only direct p children of .card?',['.card p','.card > p','p + .card','.card ~ p'],1,'The child combinator > matches direct children.'],
['CSS','Layout & responsive design','intermediate','In a row flex container, which property aligns items along the cross axis?',['justify-content','align-items','font-weight','clear'],1,'align-items controls cross-axis alignment.'],
['HTML','Forms & accessibility','advanced','Which button type prevents accidental submission inside a form?',['type="button"','type="submit"','type="text"','type="form"'],0,'type="button" has no default form submission action.'],
['HTML','Structure & semantics','intermediate','Which element marks the dominant content of the document body?',['<main>','<header>','<footer>','<style>'],0,'main identifies the document’s dominant content.'],
['CSS','Box model','intermediate','Which overflow value adds scrolling when content exceeds the box?',['visible','auto','hidden','clip'],1,'overflow: auto provides scrolling when needed.']
].map((q,i)=>({id:20+i,topic:q[0],subject:q[1],difficulty:q[2],text:q[3],answers:q[4],correct:q[5],explanation:q[6]}));
const catalog=[...QUESTIONS,...extras];let custom=[],editing=-1;
window.validLesson=p=>!!p&&p.version===1&&typeof p.name==='string'&&p.name.length<=100&&['beginner','intermediate','advanced'].includes(p.difficulty)&&(!p.pace||['practice','standard','challenge'].includes(p.pace))&&Array.isArray(p.questions)&&p.questions.length>=1&&p.questions.length<=100&&p.questions.every(q=>q&&['HTML','CSS'].includes(q.topic)&&typeof q.text==='string'&&q.text.trim().length>0&&q.text.length<=1000&&Array.isArray(q.answers)&&q.answers.length===4&&q.answers.every(a=>typeof a==='string'&&a.trim().length>0&&a.length<=300)&&Number.isInteger(q.correct)&&q.correct>=0&&q.correct<4&&typeof q.explanation==='string'&&q.explanation.length<=1500);
function selected(){const checked=[...document.querySelectorAll('#teacher-topics input:checked')].map(e=>e.value),domain=$('teacher-domain').value,level=$('teacher-difficulty').value,depth=['beginner','intermediate','advanced'];return catalog.filter(q=>(domain==='Both'||q.topic===domain)&&checked.includes(q.subject)&&depth.indexOf(q.difficulty)<=depth.indexOf(level));}
function lesson(){return {version:1,name:$('lesson-name').value.trim()||'Teacher quest',difficulty:$('teacher-difficulty').value,pace:$('teacher-pace').value,questions:[...($('use-bank').checked?selected():[]),...custom].map((q,i)=>({...q,id:i}))};}
function message(s){$('teacher-message').textContent=s;}
function preview(){const p=lesson();$('lesson-count').textContent=`${p.questions.length} questions · ${p.difficulty} practice`;const list=$('lesson-preview');list.replaceChildren();p.questions.forEach(q=>{const li=document.createElement('li');li.textContent=`${q.topic} · ${q.text}`;list.append(li);});$('launch-lesson').disabled=!validLesson(p);$('export-lesson').disabled=!validLesson(p);}
function listCustom(){const list=$('custom-list');list.replaceChildren();custom.forEach((q,i)=>{const row=document.createElement('div'),text=document.createElement('span'),edit=document.createElement('button'),remove=document.createElement('button');text.textContent=q.text;edit.textContent='Edit';remove.textContent='Remove';edit.type=remove.type='button';edit.onclick=()=>{editing=i;$('custom-text').value=q.text;$('custom-topic').value=q.topic;q.answers.forEach((a,j)=>$('choice-'+j).value=a);$('custom-correct').value=q.correct;$('custom-explanation').value=q.explanation;$('add-question').textContent='Save question';$('custom-text').focus();};remove.onclick=()=>{custom.splice(i,1);editing=-1;$('custom-form').reset();$('add-question').textContent='Add question';listCustom();preview();};row.append(text,edit,remove);list.append(row);});}
function apply(p){if(!validLesson(p))throw Error('This lesson file is invalid. Use a lesson exported from Forest Path.');$('lesson-name').value=p.name;$('teacher-difficulty').value=p.difficulty;$('teacher-pace').value=p.pace||'standard';$('use-bank').checked=false;custom=p.questions.map(q=>({...q}));editing=-1;listCustom();preview();}
function persist(){const p=lesson();if(!validLesson(p)){message('Choose a topic with questions, or add at least one custom question.');return null;}try{localStorage.setItem(storage,JSON.stringify(p));message('Teacher lesson saved on this device.');}catch{message('Device storage is unavailable. Export your lesson to keep a copy.');}return p;}
function download(p){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='forest-path-lesson.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
window.TeacherMode={open(){window.GameModes.showTeacher();preview();},current:()=>lesson()};
$('teacher-topics').innerHTML=topics.map(t=>`<label><input type="checkbox" value="${t}" checked> ${t}</label>`).join('');
for(const id of ['teacher-domain','teacher-difficulty','teacher-pace','teacher-topics','use-bank'])$(id).addEventListener('change',preview);
function preset(domain,subjects,depth='beginner'){ $('teacher-domain').value=domain;$('teacher-difficulty').value=depth;$('use-bank').checked=true;document.querySelectorAll('#teacher-topics input').forEach(c=>c.checked=subjects.includes(c.value));preview();message('Topic selection updated. Imported questions remain included; remove them below if needed.');}
$('preset-html').onclick=()=>preset('HTML',topics);$('preset-css').onclick=()=>preset('CSS',topics);$('preset-selectors').onclick=()=>preset('CSS',['Selectors']);$('preset-layout').onclick=()=>preset('CSS',['Layout & responsive design'],'intermediate');
function csvRows(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV has an unclosed quoted field.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows;}
function parseQuestions(text,isCsv){if(!isCsv){const v=JSON.parse(text);if(!Array.isArray(v))return v;return {version:1,name:'Imported questions',difficulty:$('teacher-difficulty').value,questions:v};}const rows=csvRows(text.replace(/^\uFEFF/,'')),header=rows.shift()?.map(s=>s.trim().toLowerCase());const expected=['subject','question','a','b','c','d','correct','explanation'];if(!header||expected.some(k=>!header.includes(k)))throw Error('Use the CSV template headers: subject, question, A, B, C, D, correct, explanation.');const get=(r,k)=>r[header.indexOf(k)]?.trim()||'';return {version:1,name:'Imported questions',difficulty:$('teacher-difficulty').value,questions:rows.map(r=>({topic:get(r,'subject').toUpperCase(),text:get(r,'question'),answers:['a','b','c','d'].map(k=>get(r,k)),correct:'ABCD'.indexOf(get(r,'correct').toUpperCase()),explanation:get(r,'explanation')||'Review the highlighted correct answer.'}))};}
$('question-template').onclick=()=>{const blob=new Blob(['subject,question,A,B,C,D,correct,explanation\nHTML,Which tag creates a hyperlink?,<a>,<p>,<div>,<img>,A,The a element creates a hyperlink.\nCSS,Which property changes text color?,color,margin,padding,display,A,The color property sets text color.\n'],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='forest-path-question-template.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('custom-form').onsubmit=e=>{e.preventDefault();const q={topic:$('custom-topic').value,text:$('custom-text').value.trim(),answers:[0,1,2,3].map(i=>$('choice-'+i).value.trim()),correct:+$('custom-correct').value,explanation:$('custom-explanation').value.trim()||'Review the highlighted correct answer.'};if(!validLesson({version:1,name:'Check',difficulty:'beginner',questions:[q]})){message('Enter a question and four nonempty answer choices.');return;}if(editing>=0)custom[editing]=q;else custom.push(q);editing=-1;$('custom-form').reset();$('add-question').textContent='Add question';listCustom();preview();message('Question added to this lesson.');};
$('save-lesson').onclick=persist;$('export-lesson').onclick=()=>{const p=persist();if(p)download(p);};$('launch-lesson').onclick=()=>{const p=persist();if(p)window.GameModes.startTeacher(p);};$('teacher-back').onclick=()=>window.GameModes.title();$('teacher-open').onclick=()=>TeacherMode.open();$('load-lesson').onclick=()=>$('student-file').click();$('import-lesson').onclick=()=>$('teacher-file').click();
async function importFile(file,student){try{if(!file)return;if(file.size>400000)throw Error('Lesson files must be smaller than 400 KB.');const text=await file.text(),isCsv=file.name.toLowerCase().endsWith('.csv'),raw=isCsv?null:JSON.parse(text),p=parseQuestions(text,isCsv);if(!validLesson(p))throw Error('Invalid lesson: questions must have four answers and a valid correct answer.');if(student)window.GameModes.startTeacher(p);else if(isCsv||Array.isArray(raw)){if(custom.length+p.questions.length>100)throw Error('Import would exceed 100 questions.');custom.push(...p.questions);listCustom();preview();message(`${p.questions.length} questions imported. Uncheck the library option to assign only these questions.`);}else{apply(p);message('Assignment imported. You can edit, save, or export it.');}}catch(e){$(student?'save-note':'teacher-message').textContent=e.message;}}
window.QuestionGenerator={catalog,selected,preview,preset,topics,add(questions,description){custom=questions;editing=-1;$('use-bank').checked=false;$('lesson-name').value=description.slice(0,100)||'Generated practice';listCustom();preview();message(`Prepared ${questions.length} questions. Review them below before downloading the assignment. Generation uses built-in templates and the checked question library, not a connected AI service.`);}};
$('student-file').onchange=e=>{importFile(e.target.files[0],true);e.target.value='';};$('teacher-file').onchange=e=>{importFile(e.target.files[0],false);e.target.value='';};
try{const p=JSON.parse(localStorage.getItem(storage));if(validLesson(p))apply(p);}catch{}preview();window.GameModes.title();
})();
